DROP TABLE IF EXISTS loans;

CREATE TABLE loans (
    loan_row_id BIGSERIAL PRIMARY KEY,
    as_of_date DATE,
    program TEXT,
    loan_id BIGINT,
    borrower_name TEXT,
    borrower_street TEXT,
    borrower_city TEXT,
    borrower_state TEXT,
    borrower_zip TEXT,
    lender_name TEXT,
    bank_fdic_number TEXT,
    bank_ncua_number TEXT,
    bank_street TEXT,
    bank_city TEXT,
    bank_state TEXT,
    bank_zip TEXT,
    cdc_name TEXT,
    cdc_street TEXT,
    cdc_city TEXT,
    cdc_state TEXT,
    cdc_zip TEXT,
    third_party_lender_name TEXT,
    third_party_lender_city TEXT,
    third_party_lender_state TEXT,
    third_party_dollars NUMERIC(18, 2),
    loan_amount NUMERIC(18, 2),
    sba_guaranteed_approval NUMERIC(18, 2),
    approval_date DATE,
    approval_fiscal_year INTEGER,
    disbursement_date DATE,
    processing_method TEXT,
    delivery_method TEXT,
    subprogram TEXT,
    initial_interest_rate NUMERIC(10, 4),
    fixed_or_variable_interest_ind TEXT,
    term_in_months INTEGER,
    naics_code TEXT,
    naics_description TEXT,
    franchise_code TEXT,
    franchise_name TEXT,
    project_county TEXT,
    project_state TEXT,
    sba_district_office TEXT,
    congressional_district TEXT,
    business_type TEXT,
    business_age TEXT,
    loan_status TEXT,
    paid_in_full_date DATE,
    charge_off_date DATE,
    charge_off_amount NUMERIC(18, 2),
    revolver_status TEXT,
    jobs_supported INTEGER,
    collateral_ind TEXT,
    sold_secondary_market_ind TEXT,
    source_file TEXT
);

CREATE INDEX idx_loans_borrower_state ON loans (borrower_state);
CREATE INDEX idx_loans_naics_code ON loans (naics_code);
CREATE INDEX idx_loans_approval_fiscal_year ON loans (approval_fiscal_year);
CREATE INDEX idx_loans_loan_status ON loans (loan_status);
